### ISSUE TITLE
Permission to Contribute Valuable Content (privacy policy, FAQ, about us, etc) 

### ISSUE THREAD

**Issue by RolletOso** [team2dev/steem-wallet-track#1]
Hello, 

The idea of your project is amazing and while you are doing an awesome job with technical aspects and coding, i will like to take some weight off you by offering copywriting services.

I will contribute a privacy policy which is a statement or a legal document that discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client's data.

I will contribute a compelling About Us content that will tell off your founding story, a content that will show off your the core or your project, and will answer the most pressing question new and old users may have about your project. 

I will also create  FAQ Content. I will use Frequently asked questions or Questions and Answers to list out questions and answers, all supposed to be commonly asked in some context, and pertaining to your project and more insight to the project. 

I am willing to contribute to the copywriting aspect of your project so you can put more effort on the technicalities and perform at your optimum best. 

Anticipating Your response.

Thank you.

**Comment by sogatanco** [comment]
Hello RolletOso

sorry, I'm late to reply to your comment. I am rarely online these several days .I am very happy with your offer. Please contribute as you have said above. Btw, Thank a lot for your help to our project. Nice to meet you.

Kind Regard

Team2Dev

**Comment by RolletOso** [comment]
Thanks for the reply. It is better late than never. Your project is a
fantastic one and you can try delegating some positions to someone that can
be online frequently and can create task requests on Utopian so other
programmers can also add some extra functionalities that you may want on
the project.

For me, i will start working on the content contribution and make a couple
of pull requests. Thanks
